# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: lilcham1.Encore
PackageVersion: 0.3.3
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Protocols:
- ytm-desktop
ReleaseDate: 2026-10-08
AppsAndFeaturesEntries:
- DisplayName: Encore for YouTube Music
  Publisher: lilcham1
  ProductCode: Encore
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.EdgeWebView2Runtime
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/lilcham1/youtube-music-desktop/releases/download/v0.3.3/Encore-Setup-0.3.3.exe
  InstallerSha256: 0D585F11059286559AEDC5F108899B48B09BC3086E9CB6B4E90E5CAFD946FB24
  ProductCode: Encore
ManifestType: installer
ManifestVersion: 1.12.0
