# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: lilcham1.Encore
PackageVersion: 0.3.2
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Protocols:
- ytm-desktop
ReleaseDate: 2026-10-05
AppsAndFeaturesEntries:
- DisplayName: Encore for YouTube Music
  Publisher: lilcham1
  ProductCode: Encore
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.EdgeWebView2Runtime
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/lilcham1/youtube-music-desktop/releases/download/v0.3.2/Encore-Setup-0.3.2.exe
  InstallerSha256: 9977C3079A9A02553040710E03D286E2070D89EF007164C7951A979FB8A57290
  ProductCode: Encore
ManifestType: installer
ManifestVersion: 1.12.0
